checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - tests/*
    - build/*
    - vendor/*
    - docs/*

build:

  environment:
    php: "7.0.11"

  dependencies:
    before:
      - "composer install"

  tests:
    override:
      -
        command: "php vendor/bin/phpunit"
        coverage:
          file: "build/logs/clover.xml"
          format: "php-clover"
